security:
  basic:
    enabled: false
management:
  security:
    enabled: false
    
goed:
  oauth2:
    token:
      jdbc:
        url: jdbc:h2:tcp://localhost/~/test
        driver: org.h2.Driver
        username: sa
        password:
      remote:
        endpoint: http://localhost:9999/lsso/oauth/check_token
        clientId: goedApp
        secret: secret