eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cluster1:10001/eureka/,http://cluster2:10002/eureka/
 
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG